### PR TITLE
Misc fixes: styling, getting started prompts, date update (closes 49, 48; starts on 22)

### PR DESCRIPTION
**Pull request by michellebonat**
Hey @CoralineAda I would like to help out. Here is a start, for your review.

### CODE REVIEW

**Comment by CoralineAda** [comment]
This looks great so far! Let me know when you're done and I will review and merge.

**Comment by michellebonat** [comment]
Thanks.

**Comment by michellebonat** [comment]
I'm done with this batch of updates, ready for review.

To summarize:
More styling tweaks to close issue Improve the design https://github.com/CoralineAda/opensourceforwomen.org/issues/22

Also included in PR from before:
To close issue Add helpful prompts and links in readme where junior people might get stuck #49
To close issue Update date in footer to 2017 #50 

The DataTable could use more styling I have opened a separate issue https://github.com/CoralineAda/opensourceforwomen.org/issues/51

This is how some of the updated pages look with this PR:

os4w_dashpage_styling_after

os4w_opensourcepage_styling_after

os4w_pairingpage_styling_after

os4w_mentorpage_styling_after

**Comment by CoralineAda** [comment]
Thanks so much for this! ♥️

**Comment by michellebonat** [comment]
Cheers

**Pull request merged**
