### PR TITLE
Fix missing avatar on profile page.

### PR DESCRIPTION
**Pull request by djbender**

### CODE REVIEW

**Comment by CoralineAda** [comment]
The avatar partial needs to be user-aware. As it is written right now it's going to always display the current_user avatar, but for example on the extended profile page it should be the profile's user avatar. Also the same gravatar/avatar partial should be used on the messages index and show pages.

**Comment by djbender** [comment]
ok!

**Comment by djbender** [comment]
It looks like the else branch in `app/views/messages/index.html.haml` uses a different class: `avatar-tiny` this extraction doesn't take that into consideration. should i also pass in the class strings to this partial?

**Comment by CoralineAda** [comment]
Yep, good catch.

**Comment by djbender** [comment]
Ready!

**Comment by CoralineAda** [comment]
Thanks so much Derek!

**Pull request merged**
